[build-system]
requires = [ "poetry-core>=1.0.0",]
build-backend = "poetry.core.masonry.api"

[tool.poetry]
name = "comando"
version = "0.0.1-dev"
description = "Wrapper for Python's subprocess.Popen"
authors = []
readme = "README.md"
[tool.poetry.dependencies]
python = "^3.11"

[tool.pytest.ini_options]
log_cli = true
log_cli_level = "INFO"
log_cli_format = "[%(asctime)s,%(msecs)03d] %(name)-40.40s %(levelname)s %(message)s"
addopts = "--color=yes"

[tool.poetry.group.test.dependencies]
pytest = "^7.4.2"
python-testing-utilities = "^0.6.0"

[tool.poetry.group.dev.dependencies]
python-ci-toolkit = ">=0.30.3"
